FROM golang as builder

WORKDIR /usr/src/app

COPY ./main.go .

RUN go build main.go

FROM scratch

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/main  /usr/src/app

ENTRYPOINT [ "/usr/src/app/main" ]

